### ISSUE TITLE
Server process does't exist

### ISSUE THREAD

**Issue by usamazafar63012** [SamSamhuns/restaurant_app_sh_mem#3]
I'm trying to run coordinator command but i am getting `Server process does not exist`. The command I am running is 
`./coordinator -n 5 -p 20 -t 2`.
output: 
```
Shared Memory Restaurant SHMID is 0001
Server process does not exist
Successfully exiting process with pid 472500
Shutting down restaurant normally
```
After this i am running the server command
`./server -m 0001`
output:
```
sem_open(): No such file or directory
```

**Comment by SamSamhuns** [comment]
I've updated the readme, the binaries have to be run on different terminal sessions one after another. Set `-t` to a high number when calling `./coordinator` to make sure you have enough time to call other binaries.

Check `test.sh`, which runs these binaries in the background one after another as well to get a good idea.
